<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCx6egdm\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCx6egdm/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerCx6egdm.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerCx6egdm\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerCx6egdm\appProdProjectContainer(array(
    'container.build_hash' => 'Cx6egdm',
    'container.build_id' => '99b2a1f3',
    'container.build_time' => 1555268239,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerCx6egdm');
